import { mockAttachment } from "../attachments/attachments.mocks.js";
import type { IUser } from "./user.types.js";

export const mockUser: IUser = {
	active: true,
	alias: "test",
	created_at: "2017-08-14T20:13:53Z",
	custom_role_id: null,
	default_group_id: 1873,
	details: "",
	email: "user@zendesk.com",
	external_id: "oev7jj",
	iana_time_zone: "Pacific/Pago_Pago",
	id: 3343,
	last_login_at: "2020-11-16T22:57:45Z",
	locale: "en-gb",
	locale_id: 5,
	moderator: true,
	name: "Samwise Gamgee",
	notes: "test",
	only_private_comments: false,
	organization_id: 1873,
	phone: null,
	photo: mockAttachment,
	report_csv: true,
	restricted_agent: false,
	role: "admin",
	role_type: null,
	shared: false,
	shared_agent: false,
	shared_phone_number: null,
	signature: "test",
	suspended: false,
	tags: [
		"101",
	],
	ticket_restriction: null,
	time_zone: "American Samoa",
	two_factor_auth_enabled: null,
	updated_at: "2020-11-17T00:33:55Z",
	url: "https://example.zendesk.com/api/v2/users/3343.json",
	user_fields: {
		its_remember_september: null,
		skittles: "2018-09-14T00:00:00+00:00",
		user_field_1: "101",
	},
	verified: true,
};
